air/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url

from .views import (
    import_data,
    filter_view,
    quick_add,
    stats_json,
    chart_data_json,
    AirDetectorDataChartsView,
    AirDetectorDataCreateView,
    AirDetectorDataUpdateView,
    AirDetectorDataDeleteView,
    AirDetectorDataEmailReportView,
    AirDetectorDataListJson,
)


urlpatterns = patterns('',
    url(regex=r'^import/', view=import_data, name='airdetectordata_import', ),
    url(regex=r'^filter/', view=filter_view, name='airdetectordata_filter', ),
    url(regex=r'^quick_add/', view=quick_add, name='airdetectordata_quick_add', ),
    url(regex=r'^add/', view=AirDetectorDataCreateView.as_view(),name='airdetectordata_create',),
    url(regex=r'^list_json/$', view=AirDetectorDataListJson.as_view(), name='airdetectordata_list_json',),
    url(regex=r'^chart_data_json/$', view=chart_data_json, name='chart_data_json',),
    url(regex=r'^stats_json/$', view=stats_json, name='stats_json', ),
    url(regex=r'^charts/$', view=AirDetectorDataChartsView.as_view(), name='airdetectordata_charts',),
    url(regex=r'^email_report/', view=AirDetectorDataEmailReportView.as_view(), name='airdetectordata_email_report', ),
    url(regex=r'^(?P<pk>\d+)/edit/', view=AirDetectorDataUpdateView.as_view(), name='airdetectordata_update',),
    url(regex=r'^(?P<pk>\d+)/delete/', view=AirDetectorDataDeleteView.as_view(), name='airdetectordata_delete', ),
)

core/urls.py
from django.conf.urls import patterns, url

from .views import HelpPageView


urlpatterns = patterns('',
    url(
        regex=r'^help/',
        view=HelpPageView.as_view(),
        name='help',
    ),
)

djangoiotserver/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'devices.views.index', name='index'),
    url(r'^map/$', 'devices.views.map', name='map'),
    url(r'^device/', include('devices.urls', namespace='devices')),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^help/$', 'core.views.help', name='help'),
    url(r'^support/$', 'core.views.support', name='support'),
    url(r'^explore/$', 'core.views.explore', name='explore'),
    url(r'^signup/$', 'userauth.views.signup', name='signup'),
    url(r'^signin/$', 'userauth.views.signin', name='signin'),
    url(r'^signout/$', 'userauth.views.signout', name='signout'),
    url(r'^reset/$', 'userauth.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'userauth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'userauth.views.success', name='success'),     
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^profile/$', 'settings.views.profile', name='profile'),      
    url(r'^password/$', 'settings.views.password', name='password'),   
    #url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),  
    #url(r'^api/', include(router.urls)),
    url(r'^manage/', include(admin.site.urls)),  
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

air/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from taggit.managers import TaggableManager
from model_utils.models import TimeStampedModel
from geoposition.fields import GeopositionField
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from chineseaddress.models import Address

class AirCleanerManager(models.Manager):
    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

class AirCleaner(models.Model):
    objects = AirCleanerManager()   
    id                      = models.AutoField(primary_key=True) 
    name               = models.CharField(_(u'空气净化器'),max_length=60, unique=True)   
    desc                 = models.CharField(_(u'描述'),max_length=500)    
    thumbnail       = models.ImageField(_(u'缩微图'),upload_to='device', null=True, blank=True)        
    owner             = models.ForeignKey(User, verbose_name = _(u'用户'))     
    
    date_created = models.DateField(_(u'创建日期'),null=True, blank=True)
    last_updated = models.DateTimeField(_(u'上次更新'),auto_now=True)
    notes              = models.TextField('Notes', null=False, blank=True, default='')
    tags                = TaggableManager(blank=True, help_text=None)    

    on_off             = models.BooleanField(_(u'开关机'),default=False)
    present           = models.BooleanField(_(u'存在否'),default=True)
    online             = models.BooleanField(_(u'在线'),default=True)       
    #associated     = models.ForeignKey(AirDetector, verbose_name = _(u'绑定的空气检测仪'))       
    address           = models.ForeignKey(Address, verbose_name = _(u'地址'))
    #coordinates   = GeopositionField()    
  
    def __unicode__(self):
        return self.name
   
    class Meta:
        verbose_name = _(u'空气净化器')
        verbose_name_plural = _(u'空气净化器')
        unique_together = ('name','desc')
        ordering = ['-date_created', '-last_updated']  
   
    def get_absolute_url(self):
        return reverse('air:air_detail', kwargs={'pk': self.id})
    
    def save(self, *args, **kwargs):
        super(AirCleaner, self).save(*args, **kwargs)

class Category(models.Model):
    name = models.CharField(unique=True, max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = _(u'类型') 
        ordering = ['id']

class Unit(models.Model):
    name = models.CharField(unique=True, max_length=6)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = _(u'单位') 
        ordering = ['id']

class AirDetectorManager(models.Manager):
    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)
    
class AirDetector(models.Model):
    objects             = AirDetectorManager()       
    id                      = models.AutoField(primary_key=True) 
    name               = models.CharField(_(u'空气检测仪'),max_length=60, unique=True)   
    desc                 = models.CharField(_(u'描述'),max_length=500)    
    thumbnail       = models.ImageField(_(u'缩微图'),upload_to='device', null=True, blank=True)        
    owner             = models.ForeignKey(User, verbose_name = _(u'用户'))       
    date_created = models.DateField(_(u'创建日期'),null=True, blank=True)
    last_updated = models.DateTimeField(_(u'上次更新'),auto_now=True)
    notes              = models.TextField('Notes', null=False, blank=True, default='')
    tags                = TaggableManager(blank=True, help_text=None)       
    address          = models.ForeignKey(Address, verbose_name = _(u'地址'))
    associated      = models.ForeignKey(AirCleaner, verbose_name = _(u'绑定的空气净化器'))   
    on_off              = models.BooleanField(_(u'开关机'),default=False)
    present           = models.BooleanField(_(u'存在否'),default=True)
    online             = models.BooleanField(_(u'在线'),default=True)       
    #coordinates   = GeopositionField()      

    def __unicode__(self):
        return self.name
   
    class Meta:
        verbose_name = _(u'空气检测仪')
        verbose_name_plural = _(u'空气检测仪')
        unique_together = ('name','desc')
        ordering = ['-date_created', '-last_updated']  
   
    def get_absolute_url(self):
        return reverse('air:air_detail', kwargs={'pk': self.id})
    
    def save(self, *args, **kwargs):
        super(AirDetector, self).save(*args, **kwargs)

class AirDetectorDataManager(models.Manager):

    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

    def by_date(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by date range.
        """
        resultset = self.by_user(user).filter(
            record_date__gte=start_date,
            record_date__lte=end_date,
        )

        return resultset.order_by('-record_date', '-record_time')

    def level_breakdown(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by AirDetectorData level and count the records for each level.

        The range for the different levels are specified in the user's
        settings.
        """
        user_settings = user.settings
        low = user_settings.airdetectordata_low
        high = user_settings.airdetectordata_high
        target_min = user_settings.airdetectordata_target_min
        target_max = user_settings.airdetectordata_target_max

        data = self.by_date(start_date, end_date, user)
        all_count = data.count()
        low_count = data.filter(value__lte=low).count()
        high_count = data.filter(value__gte=high).count()
        target_count = data.filter(value__gte=target_min, value__lte=target_max).count()

        result = {
            'Low': low_count,
            'High': high_count,
            'Within Target': target_count,
            'Other': all_count - (low_count + high_count + target_count)
        }

        return result

    def by_category(self, start_date, end_date, user, **kwargs):
        """
        Group objects by category and take the count.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(count=models.Count('value'))\
            .order_by('category')

    def avg_by_category(self, start_date, end_date, user):
        """
        Group objects by category and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('category')

    def avg_by_day(self, start_date, end_date, user):
        """
        Group objects by record date and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('record_date')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('record_date')

class AirDetectorData(TimeStampedModel):
    objects = AirDetectorDataManager()
    
    user = models.ForeignKey(User)    
    id= models.AutoField(primary_key=True) 
    value = models.PositiveIntegerField(_(u'数值'),validators=[MaxValueValidator(58000),MinValueValidator(0)])
    record_date = models.DateField(_(u'日期'))
    record_time = models.TimeField(_(u'时间'))
    notes = models.TextField(null=False, blank=True, verbose_name = _(u'备注'))   
    airdetector = models.ForeignKey(AirDetector,null=True, blank=True)
    category  = models.ForeignKey(Category,verbose_name = _(u'类型'))
    tags = TaggableManager(blank=True, help_text=None)

    class Meta:
        verbose_name             = _(u'空气检测仪数据')
        verbose_name_plural = _(u'空气检测仪数据')
        ordering = ['id']
        
    def __unicode__(self):
        return str(self.value)

    def save(self, *args, **kwargs):
        super(AirDetectorData, self).save(*args, **kwargs)


class Marker(models.Model):
    id= models.AutoField(primary_key=True) 
    name = models.CharField(_(u'位置'),max_length=40)
    coordinates   = GeopositionField()    
    desc = models.TextField(_(u'描述'),max_length=1000)      
    #device = models.ForeignKey(Device, verbose_name="设备",null=True, blank=True)        
   
    class Meta:
        verbose_name = _(u'位置')
        verbose_name_plural = _(u'位置')
        ordering = ['id']

    def __unicode__(self):
        return u'%s %s %s' % (self.name, self.coordinates.latitude, self.coordinates.longitude)
    
    def get_lat_lon(self):
        lat_lon = [self.geometry.latitude, self.geometry.longitude]
        return lan_lon

core/models.py
from django.db import models

core/forms.py
from django import forms

from crispy_forms.helper import FormHelper, Layout
from crispy_forms.layout import Submit, Fieldset, HTML, Field
from crispy_forms.bootstrap import FormActions


class ContactForm(forms.Form):
    email = forms.EmailField(label='Your Email Address')
    subject = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea(
        attrs={'cols': 50, 'rows': 6}))

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_class = 'col-xs-12 col-md-6'

        self. helper.layout = Layout(
            HTML('''
            {% if messages %}
            {% for message in messages %}
            <p {% if message.tags %} class="alert alert-{{ message.tags }}"\
            {% endif %}>{{ message }}</p>{% endfor %}{% endif %}
            </p>
            '''),
            Fieldset(
                'Contact Us',
                Field('email'),
                Field('subject'),
                Field('message'),
            ),
            FormActions(Submit('submit', 'Send', css_class='pull-right'))
        )

core/views.py
from django.views.generic import TemplateView, FormView
from django.contrib import messages
from django.core.mail import EmailMessage
from django.conf import settings
from braces.views import LoginRequiredMixin
from air.models import AirDetectorData
from .forms import ContactForm

class HomePageView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        context['airdetectordata_count'] = AirDetectorData.objects.count()

        return context


class HelpPageView(LoginRequiredMixin, FormView):
    success_url = '.'
    form_class = ContactForm
    template_name = 'core/help.html'

    def get_initial(self):
        return {
            'email': self.request.user.email
        }

    def form_valid(self, form):
        success_message = '''Email sent! We'll try to get back to you as
            soon as possible.'''
        messages.add_message(self.request, messages.SUCCESS, success_message)

        return super(HelpPageView, self).form_valid(form)

    def form_invalid(self, form):
        failure_message = 'Email not sent. Please try again.'
        messages.add_message(self.request, messages.WARNING, failure_message)

        return super(HelpPageView, self).form_invalid(form)

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)

        if form.is_valid():
            support_email = settings.CONTACTS['support_email']

            message = 'Sent By: %s (%s)\n\n%s' % (
                form.cleaned_data['email'],
                self.request.user.username,
                form.cleaned_data['message'])

            email = EmailMessage(
                from_email=support_email,
                subject='[Help] %s ' % form.cleaned_data['subject'],
                body=message,
                to=[support_email])

            email.send()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)

core/templates/core/dashboard.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
    <h3><span class="glyphicon glyphicon-th"></span>{% trans '仪表盘' %}</h3>
<div class="container">
{% if sticky_message %}
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        {{ sticky_message.message|safe }}
    </div>
{% endif %}

    
    <div class="row">
        <div class="col-md-6">
            <div class="panel">
                <div class="btn-group">
                    <a href="{% url 'airdetectordata_create'%}">
                    <button type="button" class="btn btn-primary">
                        <span class="fa fa-plus"></span>{% trans '输入空气检测数据' %}</button>
                    </a>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                    <span class="fa fa-stats"></span> {% trans  '报告'%}
                    <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'airdetectordata_filter' %}">{% trans  '数据筛选'%}</a></li>
                    <li><a href="{% url 'airdetectordata_charts' %}">{% trans  '数据图表'%}</a></li>
                    <li class="divider"></li>
                    <li><a href="{% url 'airdetectordata_email_report' %}">{% trans  'Email报告'%}</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="panel text-center">{% crispy form %}</div>
        </div>
    </div> <!-- end row -->



    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="row">
                <div class="col-sm-6 col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h5 class="panel-title text-center">
                                <b>{% trans  '最新数据'%}</b>
                            </h5>
                        </div>
                        <div class="panel-body">
                            <h3 id="id_latest_entry"></h3>
                            <p id="id_twitter_button" class="text-center"></p>
                        </div>
                    </div>
                </div>

                <div class="col-sm-6 col-md-6">
                    <div class="panel panel-default">
                        <div id="id_hba1c_panel" class="panel-heading" data-toggle="tooltip"
                             title="Based on the average airdetectordata from the last 90 days.">
                            <h3 class="panel-title text-center">
                                <b>{% trans  'A1C 预估'%}</b>
                            </h3>
                        </div>
                        <div class="panel-body" style="padding-bottom:24px">
                            <h3 id="id_hba1c"></h3>
                        </div>
                    </div>
                </div>
            </div> <!-- end row -->

            <div class="row">
                <div class="col-sm-12 col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title text-center">
                                <b>{% trans  '最近14天总结'%}</b>
                            </h3>
                        </div>
                        <table class="table table-condensed">
                            <tr>
                                <td><b>{% trans  '低值 '%}</b></td>
                                <td id="id_lows"></td>
                                <td><b>{% trans  '最低'%}</b></td>
                                <td id="id_lowest" align="right"></td>
                            </tr>
                            <tr>
                                <td><b>{% trans  '高值'%}</b></td>
                                <td id="id_highs"></td>
                                <td><b>{% trans  '最高'%}</b></td>
                                <td id="id_highest" align="right"></td>
                            </tr>
                            <tr>
                                <td><b>{% trans  '目标内'%}</b></td>
                                <td id="id_within_target"></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td><b>{% trans  '其他'%}</b></td>
                                <td id="id_other"></td>
                                <td><b>{% trans  '平均'%}</b></td>
                                <td id="id_average" align="right"></td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div> <!-- end row -->
        </div> <!-- end col -->

        <div class="col-sm-6 col-md-6">
            <div class="panel panel-default">
                <div id="chart_panel" class="panel-body" style="width:100%;height:343px"></div>
            </div>
        </div> <!--end col -->

    </div> <!-- end row -->
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <table id="airdetectordata_table" class="display responsive" width="100%" align="right">
                        <thead>
                            <tr>
				<th class="all">ID</th>
                                <th class="all">{% trans  '数值'%}</th>
                                <th class="all">{% trans  '类型'%}</th>
                                <th class="min-tablet">{% trans  '日期'%}</th>
                                <th class="min-tablet">{% trans  '时间'%}</th>
                                <th class="min-desktop">{% trans  '备注'%}</th>
                                <th class="min-desktop">{% trans  '标签'%}</th>
                                <th class="all"></th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block extracss %}
<link href="{{ STATIC_URL }}datatables/media/css/jquery.dataTables.css" rel="stylesheet">
<link href="{{ STATIC_URL }}datatables/extensions/Responsive/css/dataTables.responsive.css" rel="stylesheet">
<link href="{{ STATIC_URL }}datatables/extensions/TableTools/css/dataTables.tableTools.css" rel="stylesheet">
{% endblock %}

{% block extra_js %}
<script src="{{ STATIC_URL }}datatables/media/js/jquery.dataTables.js"></script>
<script src="{{ STATIC_URL }}datatables/extensions/Responsive/js/dataTables.responsive.js"></script>
<script src="{{ STATIC_URL }}datatables/extensions/TableTools/js/dataTables.tableTools.js"></script>
<script src="{{ STATIC_URL }}highcharts/js/highcharts.js"></script>
<script src="{{ STATIC_URL }}highcharts/js/modules/exporting.js"></script>
<script src="{{ STATIC_URL }}scripts/scripts.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#id_hba1c_panel').tooltip();

    // Update stats in panels
    var statsUrl = "{% url 'stats_json' %}";
    function loadStats() {
        $.getJSON(statsUrl,
            function(data) {
                document.getElementById('id_latest_entry').innerHTML = data['stats']['latest_entry']['value'];
                document.getElementById('id_latest_entry').className = "text-center " + data['stats']['latest_entry']['css_class'];

                document.getElementById('id_hba1c').innerHTML = data['stats']['hba1c']['value'];
                document.getElementById('id_hba1c').className = "text-center " + data['stats']['hba1c']['css_class'];

                /*document.getElementById('id_num_records').innerHTML =
                    data['stats']['num_records'];*/

                document.getElementById('id_lowest').innerHTML = data['stats']['breakdown']['lowest']['value'];
                document.getElementById('id_lowest').className = data['stats']['breakdown']['lowest']['css_class'];
                document.getElementById('id_highest').innerHTML = data['stats']['breakdown']['highest']['value'];
                document.getElementById('id_highest').className = data['stats']['breakdown']['highest']['css_class'];
                document.getElementById('id_average').innerHTML = data['stats']['breakdown']['average']['value'];
                document.getElementById('id_average').className = data['stats']['breakdown']['average']['css_class'];
                document.getElementById('id_highs').innerHTML = data['stats']['breakdown']['highs'];
                document.getElementById('id_lows').innerHTML = data['stats']['breakdown']['lows'];
                document.getElementById('id_within_target').innerHTML = data['stats']['breakdown']['within_target'];
                document.getElementById('id_other').innerHTML = data['stats']['breakdown']['other'];

                var twitter_text = "#bgnow "
                    + data['stats']['latest_entry']['value']
                    + " (" + data['stats']['latest_entry']['record_time']
                    + ") " + data['stats']['latest_entry']['notes'];
                // Remove leading and trailing spaces
                twitter_text = twitter_text.trim();
                updateTwitterValues(twitter_text, 'airdetectordatatracker');
            }
        )};

    loadStats();


    // airdetectordata Average by Day chart
     var avgByDayOptions = {
        credits: {
            enabled: false
        },
        chart: {
            renderTo: 'chart_panel',
            type: 'line',
        },
        legend: {enabled: false},
        title: {text: '每日空气监测数据平均值'},
        subtitle: {text: '最近14天数值'},
        xAxis: {title: {text: null}, labels: {rotation: -45}},
        yAxis: {title: {text: null}},
        series: [{}],
    };

    var chartDataUrl = "{% url 'chart_data_json' %}?name=avg_by_day&days=14";
    function loadChart() {
        $.getJSON(chartDataUrl,
            function(data) {
                avgByDayOptions.xAxis.categories = data['chart_data']['dates'];
                avgByDayOptions.series[0].name = 'Avg AirDetectorData ({{ user.settings.airdetectordata_unit }})';
                avgByDayOptions.series[0].data = data['chart_data']['values'];
                var chart = new Highcharts.Chart(avgByDayOptions);
         });
     }

    loadChart();


    var oTable = $('#airdetectordata_table').dataTable( {
        "sDom": 'T<"container">lfrtip',
        "tableTools": {
            "sSwfPath": "{{ STATIC_URL }}datatables/extensions/TableTools/swf/copy_csv_xls_pdf.swf",
		        "aButtons": [ "csv", "pdf" ]
        },
        "aLengthMenu": [
            [10, 15, 25, 50, 75, 100],
            [10, 15, 25, 50, 75, 100],
        ],
        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "{% url 'airdetectordata_list_json' %}",
        "aaSorting": [ [2,'desc'], [3,'desc'] ],

        // Disable sorting for the Tags and Actions columns.
        "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 5, 6 ] } ]
    } );

    // Add the airdetectordata value and refresh the table data
    var frm = $('#quick_add_form');
    frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: "{% url 'airdetectordata_quick_add' %}",
            data: frm.serialize(),
            success: function (data) {
                var message = jQuery.parseJSON(data);
                if (message['success']) {
                    // Reload the table data. This function is located in
                    // scripts/scripts.js.
                    oTable.fnReloadAjax();

                    // Reload the chart and stats panels
                    loadStats();
                    loadChart();

                    document.getElementById('quick_add_form').reset();
                    $('#id_value').focus();

                    // Re-enable the submit button.
                    $('#submit-id-submit').prop('disabled', false);
                }
                else {
                    alert(message['error']);
                    $('#id_value').focus().select();

                    // Re-enable the submit button.
                    $('#submit-id-submit').prop('disabled', false);
                }
            },
            error: function(data) {
                alert('Sorry, something went wrong. Please try again.');
            }
        });
        return false;
    });


    // For Twitter button
    function updateTwitterValues(text, via) {
      $('#id_twitter_button').html('<a href="https://twitter.com/share?url=/" class="twitter-share-button" data-dnt="true" data-text="' + text +'" data-count="none" data-via="' + via +'">Tweet</a>');
      twttr.widgets.load();
    }

    !function(d,s,id){
    var js,fjs=d.getElementsByTagName(s)[0];

    if(!d.getElementById(id)){
        js=d.createElement(s);
        js.id=id;
        js.src="https://platform.twitter.com/widgets.js";
        fjs.parentNode.insertBefore(js,fjs);
    }}

    (document,"script","twitter-wjs");
} );
</script>
{% endblock %}

core/templates/core/help.html
{% extends 'base.html' %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
   <h3><span class="glyphicon glyphicon-question-sign"></span>{% trans '帮助' %}</h3>
    {% crispy form %}
{% endblock %}