air/urls.py
# -*- coding: UTF-8 -*-
from django.conf.urls import patterns, url

from .views import (
    import_data,
    filter_view,
    quick_add,
    stats_json,
    chart_data_json,
    AirDetectorDataChartsView,
    AirDetectorDataCreateView,
    AirDetectorDataUpdateView,
    AirDetectorDataDeleteView,
    AirDetectorDataEmailReportView,
    AirDetectorDataListJson,
)


urlpatterns = patterns('',
    url(regex=r'^import/', view=import_data, name='airdetectordata_import', ),
    url(regex=r'^filter/', view=filter_view, name='airdetectordata_filter', ),
    url(regex=r'^quick_add/', view=quick_add, name='airdetectordata_quick_add', ),
    url(regex=r'^add/', view=AirDetectorDataCreateView.as_view(),name='airdetectordata_create',),
    url(regex=r'^list_json/$', view=AirDetectorDataListJson.as_view(), name='airdetectordata_list_json',),
    url(regex=r'^chart_data_json/$', view=chart_data_json, name='chart_data_json',),
    url(regex=r'^stats_json/$', view=stats_json, name='stats_json', ),
    url(regex=r'^charts/$', view=AirDetectorDataChartsView.as_view(), name='airdetectordata_charts',),
    url(regex=r'^email_report/', view=AirDetectorDataEmailReportView.as_view(), name='airdetectordata_email_report', ),
    url(regex=r'^(?P<pk>\d+)/edit/', view=AirDetectorDataUpdateView.as_view(), name='airdetectordata_update',),
    url(regex=r'^(?P<pk>\d+)/delete/', view=AirDetectorDataDeleteView.as_view(), name='airdetectordata_delete', ),
)

djangoiotserver/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'devices.views.index', name='index'),
    url(r'^map/$', 'devices.views.map', name='map'),
    url(r'^device/', include('devices.urls', namespace='devices')),
    url(r'^about/$', 'core.views.about', name='about'),
    url(r'^help/$', 'core.views.help', name='help'),
    url(r'^support/$', 'core.views.support', name='support'),
    url(r'^explore/$', 'core.views.explore', name='explore'),
    url(r'^signup/$', 'userauth.views.signup', name='signup'),
    url(r'^signin/$', 'userauth.views.signin', name='signin'),
    url(r'^signout/$', 'userauth.views.signout', name='signout'),
    url(r'^reset/$', 'userauth.views.reset', name='reset'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'userauth.views.reset_confirm', name='password_reset_confirm'),
    url(r'^success/$', 'userauth.views.success', name='success'),     
    url(r'^settings/', include('settings.urls', namespace='settings')),
    url(r'^profile/$', 'settings.views.profile', name='profile'),      
    url(r'^password/$', 'settings.views.password', name='password'),   
    #url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),  
    #url(r'^api/', include(router.urls)),
    url(r'^manage/', include(admin.site.urls)),  
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

air/models.py
# -*- coding: UTF-8 -*-
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from taggit.managers import TaggableManager
from model_utils.models import TimeStampedModel
from geoposition.fields import GeopositionField
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from chineseaddress.models import Address

class AirCleanerManager(models.Manager):
    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

class AirCleaner(models.Model):
    objects = AirCleanerManager()   
    id                      = models.AutoField(primary_key=True) 
    name               = models.CharField(_(u'空气净化器'),max_length=60, unique=True)   
    desc                 = models.CharField(_(u'描述'),max_length=500)    
    thumbnail       = models.ImageField(_(u'缩微图'),upload_to='device', null=True, blank=True)        
    owner             = models.ForeignKey(User, verbose_name = _(u'用户'))     
    
    date_created = models.DateField(_(u'创建日期'),null=True, blank=True)
    last_updated = models.DateTimeField(_(u'上次更新'),auto_now=True)
    notes              = models.TextField('Notes', null=False, blank=True, default='')
    tags                = TaggableManager(blank=True, help_text=None)    

    on_off             = models.BooleanField(_(u'开关机'),default=False)
    present           = models.BooleanField(_(u'存在否'),default=True)
    online             = models.BooleanField(_(u'在线'),default=True)       
    #associated     = models.ForeignKey(AirDetector, verbose_name = _(u'绑定的空气检测仪'))       
    address           = models.ForeignKey(Address, verbose_name = _(u'地址'))
    #coordinates   = GeopositionField()    
  
    def __unicode__(self):
        return self.name
   
    class Meta:
        verbose_name = _(u'空气净化器')
        verbose_name_plural = _(u'空气净化器')
        unique_together = ('name','desc')
        ordering = ['-date_created', '-last_updated']  
   
    def get_absolute_url(self):
        return reverse('air:air_detail', kwargs={'pk': self.id})
    
    def save(self, *args, **kwargs):
        super(AirCleaner, self).save(*args, **kwargs)

class Category(models.Model):
    name = models.CharField(unique=True, max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = _(u'类型') 
        ordering = ['id']

class Unit(models.Model):
    name = models.CharField(unique=True, max_length=6)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = _(u'单位') 
        ordering = ['id']

class AirDetectorManager(models.Manager):
    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)
    
class AirDetector(models.Model):
    objects             = AirDetectorManager()       
    id                      = models.AutoField(primary_key=True) 
    name               = models.CharField(_(u'空气检测仪'),max_length=60, unique=True)   
    desc                 = models.CharField(_(u'描述'),max_length=500)    
    thumbnail       = models.ImageField(_(u'缩微图'),upload_to='device', null=True, blank=True)        
    owner             = models.ForeignKey(User, verbose_name = _(u'用户'))       
    date_created = models.DateField(_(u'创建日期'),null=True, blank=True)
    last_updated = models.DateTimeField(_(u'上次更新'),auto_now=True)
    notes              = models.TextField('Notes', null=False, blank=True, default='')
    tags                = TaggableManager(blank=True, help_text=None)       
    address          = models.ForeignKey(Address, verbose_name = _(u'地址'))
    associated      = models.ForeignKey(AirCleaner, verbose_name = _(u'绑定的空气净化器'))   
    on_off              = models.BooleanField(_(u'开关机'),default=False)
    present           = models.BooleanField(_(u'存在否'),default=True)
    online             = models.BooleanField(_(u'在线'),default=True)       
    #coordinates   = GeopositionField()      

    def __unicode__(self):
        return self.name
   
    class Meta:
        verbose_name = _(u'空气检测仪')
        verbose_name_plural = _(u'空气检测仪')
        unique_together = ('name','desc')
        ordering = ['-date_created', '-last_updated']  
   
    def get_absolute_url(self):
        return reverse('air:air_detail', kwargs={'pk': self.id})
    
    def save(self, *args, **kwargs):
        super(AirDetector, self).save(*args, **kwargs)

class AirDetectorDataManager(models.Manager):

    def by_user(self, user, **kwargs):
        """
        Filter objects by the 'user' field.
        """
        return self.select_related().filter(user=user)

    def by_date(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by date range.
        """
        resultset = self.by_user(user).filter(
            record_date__gte=start_date,
            record_date__lte=end_date,
        )

        return resultset.order_by('-record_date', '-record_time')

    def level_breakdown(self, start_date, end_date, user, **kwargs):
        """
        Filter objects by AirDetectorData level and count the records for each level.

        The range for the different levels are specified in the user's
        settings.
        """
        user_settings = user.settings
        low = user_settings.airdetectordata_low
        high = user_settings.airdetectordata_high
        target_min = user_settings.airdetectordata_target_min
        target_max = user_settings.airdetectordata_target_max

        data = self.by_date(start_date, end_date, user)
        all_count = data.count()
        low_count = data.filter(value__lte=low).count()
        high_count = data.filter(value__gte=high).count()
        target_count = data.filter(value__gte=target_min, value__lte=target_max).count()

        result = {
            'Low': low_count,
            'High': high_count,
            'Within Target': target_count,
            'Other': all_count - (low_count + high_count + target_count)
        }

        return result

    def by_category(self, start_date, end_date, user, **kwargs):
        """
        Group objects by category and take the count.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(count=models.Count('value'))\
            .order_by('category')

    def avg_by_category(self, start_date, end_date, user):
        """
        Group objects by category and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('category__name')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('category')

    def avg_by_day(self, start_date, end_date, user):
        """
        Group objects by record date and take the average of the values.
        """
        data = self.by_date(start_date, end_date, user)

        return data.values('record_date')\
            .annotate(avg_value= models.Avg('value'))\
            .order_by('record_date')

class AirDetectorData(TimeStampedModel):
    objects = AirDetectorDataManager()
    
    user = models.ForeignKey(User)    
    id= models.AutoField(primary_key=True) 
    value = models.PositiveIntegerField(_(u'数值'),validators=[MaxValueValidator(58000),MinValueValidator(0)])
    record_date = models.DateField(_(u'日期'))
    record_time = models.TimeField(_(u'时间'))
    notes = models.TextField(null=False, blank=True, verbose_name = _(u'备注'))   
    airdetector = models.ForeignKey(AirDetector,null=True, blank=True)
    category  = models.ForeignKey(Category,verbose_name = _(u'类型'))
    tags = TaggableManager(blank=True, help_text=None)

    class Meta:
        verbose_name             = _(u'空气检测仪数据')
        verbose_name_plural = _(u'空气检测仪数据')
        ordering = ['id']
        
    def __unicode__(self):
        return str(self.value)

    def save(self, *args, **kwargs):
        super(AirDetectorData, self).save(*args, **kwargs)


class Marker(models.Model):
    id= models.AutoField(primary_key=True) 
    name = models.CharField(_(u'位置'),max_length=40)
    coordinates   = GeopositionField()    
    desc = models.TextField(_(u'描述'),max_length=1000)      
    #device = models.ForeignKey(Device, verbose_name="设备",null=True, blank=True)        
   
    class Meta:
        verbose_name = _(u'位置')
        verbose_name_plural = _(u'位置')
        ordering = ['id']

    def __unicode__(self):
        return u'%s %s %s' % (self.name, self.coordinates.latitude, self.coordinates.longitude)
    
    def get_lat_lon(self):
        lat_lon = [self.geometry.latitude, self.geometry.longitude]
        return lan_lon

air/templates/air/airdetectordata_charts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block content %}
<br>
<br>
<h3>
    <span class="fa fa-filter"></span>{% trans  '数据图表'%}
    <small>
        <a href="{% url 'airdetectordata_charts' %}"></a> {% trans  '数据筛选'%}
        | <a href="{% url 'airdetectordata_email_report' %}">{% trans  'Email报告'%}</a>
    </small>
</h3>

<div class="container">
    <div class="row">
        <div class ="col-sm-6 col-md-6">
            <div id="accordion3" class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-target="#collapseBody3">
                        AirDetectorData Level Breakdown
                        <span class="fa fa-chevron-up pull-right"></span>
                    </a>
                </h4>
            </div>
            <div id="collapseBody3" class="panel-collapse collapse in">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <select id="levelBreakdownSelect" class="form-control input-sm">
                            <option value=7>Last 7 Days</option>
                            <option value=14>Last 14 Days</option>
                            <option value=30>Last 30 Days</option>
                            <option value=90>Last 90 Days</option>
                        </select>
                    </div>
                </div>
                <div id="levelBreakdownPanel" class="panel-body"></div>
            </div>
            </div>
        </div>

        <div class ="col-sm-6 col-md-6">
            <div id="accordion4" class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-target="#collapseBody4">
                        Category Breakdown
                        <span class="fa fa-chevron-up pull-right"></span>
                    </a>
                </h4>
            </div>
            <div id="collapseBody4" class="panel-collapse collapse in">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <select id="countByCategorySelect" class="form-control input-sm">
                            <option value=7>Last 7 Days</option>
                            <option value=14>Last 14 Days</option>
                            <option value=30>Last 30 Days</option>
                            <option value=90>Last 90 Days</option>
                        </select>
                    </div>
                </div>
                <div id="countByCategoryPanel" class="panel-body">
                </div>
            </div>
            </div>
        </div>
    </div> <!-- end row -->
</div>

<div class="container">
    <div class="row">
        <div class ="col-sm-6 col-md-6">
            <div id="accordion2" class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-target="#collapseBody2">
                        Average AirDetectorData by Day
                        </span><span class="fa fa-chevron-up pull-right"></span>
                    </a>
                </h4>
            </div>
            <div id="collapseBody2" class="panel-collapse collapse in">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <select id="avgByDaySelect" class="form-control input-sm">
                            <option value=7>Last 7 Days</option>
                            <option value=14>Last 14 Days</option>
                            <option value=30>Last 30 Days</option>
                        </select>
                    </div>
                </div>
                <div id="avgByDayPanel" class="panel-body"></div>
            </div>
            </div>
        </div>

        <div class ="col-sm-6 col-md-6">
            <div id="accordion1" class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-target="#collapseBody1">
                        Average AirDetectorData by Category
                        <span class="fa fa-chevron-up pull-right"></span>
                    </a>
                </h4>
            </div>
            <div id="collapseBody1" class="panel-collapse collapse in">
                <div class="row">
                    <div class="col-sm-4 col-md-4">
                        <select id="avgByCategorySelect" class="form-control input-sm">
                            <option value=7>Last 7 Days</option>
                            <option value=14>Last 14 Days</option>
                            <option value=30>Last 30 Days</option>
                            <option value=90>Last 90 Days</option>
                        </select>
                    </div>
                </div>
                <div id="avgByCategoryPanel" class="panel-body"></div>
            </div>
            </div>
        </div>
    </div> <!-- end row -->
</div>
{% endblock %}

{% block extra_js %}
<script src="{% static 'highcharts/js/highcharts.js' %}"></script>
<script src="{% static 'highcharts/js/modules/exporting.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {
    // For changing the icon in the Options panel
    $('.collapse').on('shown.bs.collapse', function(){
        $(this).parent().find(".fa-chevron-down")
            .removeClass("fa-chevron-down")
            .addClass("fa-chevron-up");
    }).on('hidden.bs.collapse', function(){
        $(this).parent().find(".fa-chevron-up")
            .removeClass("fa-chevron-up")
            .addClass("fa-chevron-down");
    });


    var jsonUrl = '{% url 'chart_data_json' %}'

    // Glucose Average by Category
    var avgByCategoryOptions = {
        credits: {
            enabled: false
        },
        chart: {
            renderTo: 'avgByCategoryPanel',
            type: 'column'
        },
        legend: {enabled: false},
        title: {text: null},
        xAxis: {},
        yAxis: {title: {text: null}},
        series: [{}],
    };

    function loadAvgByCategory(path){
        $.getJSON(path,
            function(data) {
                avgByCategoryOptions.xAxis.categories = data['chart_data']['categories'];
                avgByCategoryOptions.series[0].name = 'Avg Glucose ({{ user.settings.airdetectordata_unit }})';
                avgByCategoryOptions.series[0].data = data['chart_data']['values'];
                var chart = new Highcharts.Chart(avgByCategoryOptions);
        });
    }

    $('#avgByCategorySelect').change(function(){
        var days = $('#avgByCategorySelect').val();
        var path = jsonUrl + '?name=avg_by_category&days=' + days;
        loadAvgByCategory(path);
    });
    

    // Glucose Average by Day
     var avgByDayOptions = {
        credits: {
            enabled: false
        },
        chart: {
            renderTo: 'avgByDayPanel',
            type: 'area',
        },
        legend: {enabled: false},
        title: {text: null},
        xAxis: {labels: {rotation: -45}},
        yAxis: {title: {text: null}},
        series: [{}],
    };

    function loadAvgByDay(path){
        $.getJSON(path,
            function(data) {
                avgByDayOptions.xAxis.categories = data['chart_data']['dates'];
                avgByDayOptions.series[0].name = 'Avg Glucose ({{ user.settings.airdetectordata_unit }})';
                avgByDayOptions.series[0].data = data['chart_data']['values'];
                var chart = new Highcharts.Chart(avgByDayOptions);
        });
    }

    $('#avgByDaySelect').change(function(){
        var days = $('#avgByDaySelect').val();
        var path = jsonUrl + '?name=avg_by_day&days=' + days;
        loadAvgByDay(path);
    });


    // Glucose Levels Breakdown
    var levelBreakdownOptions = {
        credits: {
            enabled: false
        },
        chart: {
            renderTo: 'levelBreakdownPanel',
        },
        title: {text: null},
        series: [{type: 'pie', name: 'Glucose Count'}],
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    color: '#000000',
                    connectorColor: '#000000',
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                },
                showInLegend: true
            }
        },
    };
    
    function loadLevelBreakdown(path){
        $.getJSON(path,
            function(data) {
                levelBreakdownOptions.series[0].data = data['chart_data'];
                var chart = new Highcharts.Chart(levelBreakdownOptions);
        });
    }
    
    $('#levelBreakdownSelect').change(function(){
        var days = $('#levelBreakdownSelect').val();
        var path = jsonUrl + '?name=level_breakdown&days=' + days;
        loadLevelBreakdown(path);
    });


    // Category Breakdown
     var countByCategoryOptions = {
        credits: {
            enabled: false
        },
        chart: {
            renderTo: 'countByCategoryPanel',
        },
        title: {text: null},
        series: [{type: 'pie', name: 'Glucose Count'}],
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    color: '#000000',
                    connectorColor: '#000000',
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %'
                },
                showInLegend: true
            }
        },
    };

    function loadCountByCategory(path){
        $.getJSON(path,
            function(data) {
                countByCategoryOptions.series[0].innerSize = '40%';
                countByCategoryOptions.series[0].data = data['chart_data'];
                var chart = new Highcharts.Chart(countByCategoryOptions);
        });
    }

    $('#countByCategorySelect').change(function(){
        var days = $('#countByCategorySelect').val();
        var path = jsonUrl + '?name=count_by_category&days=' + days;
        loadCountByCategory(path);
    });


    // Initial loading of the charts
    loadAvgByCategory(jsonUrl  + '?name=avg_by_category&days='
        + $('#avgByCategorySelect').val());
    loadAvgByDay(jsonUrl + '?name=avg_by_day&days='
        + $('#avgByDaySelect').val());
    loadLevelBreakdown(jsonUrl + '?name=level_breakdown&days='
        + $('#levelBreakdownSelect').val());
    loadCountByCategory(jsonUrl + '?name=count_by_category&days='
        + $('#countByCategorySelect').val());
});
</script>
{% endblock %}

air/templates/air/airdetectordata_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
<br>
<br>
<br>
    <span class="fa fa-times"></span> Delete airdetectordata</h3>
<div class="form-group">
    <form action="{% url 'airdetectordata_delete' airdetectordata.id %}" method="post">
        {% csrf_token %}
        <p>Deleting airdetectordata <b>{{ airdetectordata.value }} ({{ airdetectordata.category }})</b>. Are you sure?</p>
        <br>
        <button type="submit" class="btn btn-primary" action="submit">Yes, I'm sure</button>
        <button type="button" class="btn" onclick="location.href=&quot;{% url 'dashboard' %}&quot;;">Cancel</button>
    </form>
</div>
{% endblock %}

air/templates/air/airdetectordata_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
    <h3><span class="fa fa-plus"></span> Add AirDetectorData</h3>
   {% crispy form %}
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(function () {
    $('#id_record_date').datetimepicker({
        pickTime: false
    });

    // Sets the value of the submit_button_type field if the 'Submit & Add
    // Another button is clicked.
    $('#submit-id-submit_and_add').click(function() {
        $('#id_submit_button_type').val('submit_and_add');
    });
});
</script>
{% endblock %}

air/templates/air/airdetectordata_email_report.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block extracss %}
<link href="{% static 'datetimepicker/css/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
<h3>
    <span class="fa fa-envelope"></span> {% trans  'Email报告'%}
    <small>
        <a href="{% url 'airdetectordata_filter' %}">{% trans  '数据筛选'%}</a>
        | <a href="{% url 'airdetectordata_charts' %}">{% trans  '数据图表'%}</a>
    </small>
</h3>
<div class="container">
   {% crispy form %}
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(function () {
    $('#id_start_date').datetimepicker({
        pickTime: false
    });

    $('#id_end_date').datetimepicker({
        pickTime: false
    });
});
</script>
{% endblock %}

air/templates/air/airdetectordata_import.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
<h3>
    <span class="fa fa-upload"></span> Import Data from CSV
    <small>
        <a href="{% url 'help' %}">Help</a>
    </small>
</h3>
<div class="container">
  <h3>Instructions</h3>
  <p>
    To properly import your data, the CSV file must follow
    this order and format:
    <ol>
    <li>Value</li>
    <li>Category (if no matching category in our system,
    'No Category' will be assigned)</li>
    <li>Date (in m/d/yyyy format, e.g. 5/6/2014 or
    05/06/2014)</li>
    <li> Time (in h:m am/pm format, e.g. 8:01 AM or 08:01 PM)</li>
    <li>Notes</li>
    </ol>
    You can also download this template as a guide:
    <a href="{% static 'samples/csv_import_template.csv' %}">csv_import_template.csv</a>
  </p>
 {% crispy form %}
</div>
{% endblock %}

air/templates/air/airdetectordata_update.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}



{% load crispy_forms_tags %}

{% block content %}
<br>
<br>
    <h3><span class="fa fa-pencil"></span> Edit AirDetectorData</h3>
   {% crispy form %}
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(function () {
    $('#id_record_date').datetimepicker({
        pickTime: false
    });
});
</script>
{% endblock %}